### ISSUE TITLE
how to connect to clickhouse with password?

### ISSUE THREAD

**Issue by 545314690** [VaBezruchko/spark-clickhouse-connector#2]
Where to set the username and password param when connect to my clickhouse ?

**Comment by VaBezruchko** [comment]
I've added two properties for SparkConf: 'spark.clickhouse.user' and 'spark.clickhouse.password'.

**Comment by 545314690** [comment]
> I've added two properties for SparkConf: 'spark.clickhouse.user' and 'spark.clickhouse.password'.

It works , thank you.
