### ISSUE TITLE
Using the ClickHouse single server

### ISSUE THREAD

**Issue by dars1608** [VaBezruchko/spark-clickhouse-connector#4]
In this method: `io.clickhouse.spark.connector.SparkClickhouseFunctions#clickhouseTable(query: String, cluster: String)` parameter `cluster` is not optional.

Is there a way (or workaround) to read from ClickHouse single server.

**Comment by VaBezruchko** [comment]
I've added function `SparkClickhouseFunctions#clickhouseTableWithoutCluster` for this purpose. You can try new functionality.

**Comment by dars1608** [comment]
Thank you, I'll try it.
